name: Deploy Nest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, nest]
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Versión de node
        run: node -v
        shell: powershell

      - name: Instalar dependencias
        run: npm ci
        shell: powershell

      - name: Build
        run: npm run build
        shell: powershell

      - name: Confirmar que dist se generó
        run: dir dist
        shell: powershell

      - name: Debug contexto del runner
        run: |
          whoami
          echo "PM2_HOME = $env:PM2_HOME"
          Get-Command pm2 | Select-Object Source
          pm2 list
        shell: powershell