name: Deploy Nest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, nest]
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Versión de node
        run: node -v
        shell: powershell

      - name: Instalar dependencias
        run: npm ci
        shell: powershell

      - name: Build
        run: npm run build
        shell: powershell

      - name: Confirmar que dist se generó
        run: dir dist
        shell: powershell

      - name: Redeploy con PM2
        shell: powershell
        env:
          PM2_HOME: D:\Node\pm2-nest
        run: |
          pm2 startOrRestart ecosystem.config.js --update-env
          pm2 save